### ISSUE TITLE
A few issues

### ISSUE THREAD

**Issue by robinwhittleton** [erinendrei/henry-handel-richardson_the-getting-of-wisdom#1]
**content.opf**
- We should add author full name: Ethel Florence Lindesay Richardson
- “where she encounters prejudice and other forms of wisdom” <- implies prejudice is a form of wisdom?
- Künstlerroman isn’t in MW, so let’s give it a `lang="de"`

**epigraph**
- Bible chapter and verse should be arabic numerals: https://standardebooks.org/manual/1.8.0/single-page#8.17.4.1.1

**Comment by erinendrei** [comment]
Thanks, Robin. This SEMoS rule says not to include the pseudonym: https://standardebooks.org/manual/1.8.0/single-page#9.11.4
Do you still want me to include it as the full name?

Part of the novel is that she doesn't seem to gain genuine wisdom at all, but rather "conventional wisdom" or "received wisdom"; I was trying to imply that (because as you suggest, prejudice isn't a form of wisdom) but obviously failed :) Would the following work instead: "A girl from rural Victoria is sent to a prestigious boarding school in Melbourne, where she grows in prejudice and deceitfulness, and in favour with almost nobody."

Have added the language tag and fixed the Bible citation. Lint flagged the other one from Genesis, so I'm not sure why it didn't flag Proverbs, I'll look into that.

**Comment by robinwhittleton** [comment]
Sounds like a better short description, yep 🙂

I hadn’t seen that rule on the full name so good catch. Keep it as it is.

Once you’ve made the description change I’ll let Alex know that we’re ready.

**Comment by erinendrei** [comment]
Thanks Robin. I've changed the short description and cut the long description slightly as well.

**Comment by robinwhittleton** [comment]
Better, thanks. (Incidentally, I still can’t get over how good a name Bearstar Bearsson (trans.) is! He’s been on my todo list for a while.)

**Comment by erinendrei** [comment]
Haha, isn't it! I haven't read him but submitted The Fisher Girl to the first production list, will be interested if someone picks it up (or another of his works) :)
